# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-28 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbs', '0002_auto_20160928_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='群名字')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='群简介')),
                ('max_members', models.IntegerField(default=200)),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admins', to='bbs.UserProfile', verbose_name='群管理员')),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to='bbs.UserProfile', verbose_name='群成员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='群主')),
            ],
            options={
                'verbose_name_plural': '聊天群',
                'verbose_name': '聊天群',
            },
        ),
    ]
