# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webgroup',
            options={'verbose_name': '群组', 'verbose_name_plural': '群组'},
        ),
    ]
