# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('priority', models.IntegerField(default=9999, verbose_name='优先级')),
                ('head_img', models.ImageField(blank=True, height_field=150, null=True, upload_to='article/%Y/%m/%d', width_field=150)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pulished', '已发布'), ('hidden', '隐藏')], default='pulished', max_length=50)),
            ],
            options={
                'verbose_name_plural': '帖子',
                'ordering': ['id'],
                'verbose_name': '帖子',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='分类名称')),
                ('brief', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('set_as_top_menu', models.BooleanField(default=False, verbose_name='是否展示')),
                ('position_index', models.SmallIntegerField(verbose_name='位置展示')),
            ],
            options={
                'verbose_name_plural': '分类信息',
                'ordering': ['position_index'],
                'verbose_name': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(choices=[(1, '评论'), (2, '点赞')], default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Article', verbose_name='所属文章')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_children', to='bbs.Comment')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile'),
        ),
        migrations.AddField(
            model_name='category',
            name='admins',
            field=models.ManyToManyField(blank=True, to='bbs.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Category'),
        ),
    ]
